[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# TWO CARDS
[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/overrides.lua"]'''
pattern = "local parts = {}"
position = "after"
match_indent = true
payload = '''
local hand_copy = {}
for i,_ in ipairs(hand) do
    hand_copy[#hand_copy + 1] = hand[i]
    if SMODS.has_enhancement(hand[i], "m_thel_twocards") then
        hand_copy[#hand_copy + 1] = hand[i]
    end
end
'''

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/overrides.lua"]'''
pattern = "parts[v] = SMODS.PokerHandParts[v].func(hand) or {}"
position = "at"
match_indent = true
payload = "parts[v] = SMODS.PokerHandParts[v].func(hand_copy) or {}"

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/overrides.lua"]'''
pattern = "results[k] = _hand.evaluate(parts, hand) or {}"
position = "at"
match_indent = true
payload = "results[k] = _hand.evaluate(parts, hand_copy) or {}"